-- Run this in Supabase SQL Editor after creating a PRIVATE bucket named:
-- tender-documents
--
-- Do not create anon or authenticated policies for this bucket. Firebase callable
-- functions verify the current Firestore role and use the Supabase service role
-- only on the server to issue short-lived signed upload/download URLs.
--
-- Existing public objects require a reviewed migration before changing the live
-- bucket. See docs/DEPLOYMENT.md; this file intentionally grants no public access.
